### PR TITLE
Integrate zhuyin (bopomofo)

### PR DESCRIPTION
**Pull request by ribbanya**
Hello. I think this deck is amazing, but I don't like pinyin very much so I added [zhuyin](https://en.wikipedia.org/wiki/Bopomofo) to it.

Currently, input checking of `{{type:Zhuyin}}` is not supported, but I would like to implement it. First, however, I wanted to discuss how to integrate these changes, as there are many ways.

Possibilities include:
1. Integrate at gen time using command line options or a config file, and provide separate AnkiWeb entries
2. Integrate at the user level, by allowing the user to manually edit `display` CSS properties
3. Generate divergent card types for pinyin and zhuyin in the same `apkg`
4. Merge both lettering systems into one workflow (how it is currently)
5. Maintain the two packages as separate, on separate forks

Personally, I would prefer something closer to (2) or (4), but I am of course open to discussion.

### CODE REVIEW

**Comment by helq** [comment]
Hi @ribbanya, I like a lot what you have done, correcting misspellings and improving the CSS. I only have two small comments: I like to type annotate all functions, so that mypy is able to show me errors before running code (if you don't know mypy, I recommend you to check it out); and, I would like to replace the `exit(1)` for a `raise Exception(f"{pinyin} isn't a pinyin")`. The behaviour is pretty much equivalent, but I prefer to raise exceptions than stopping the execution.

I am inclined for option 2 too. Preferably, everything should be packed in a single file and the user should be able to tweak as they please. Adding a few KB to your phone/PC for support on both pinyin and bomopofo shouldn't be a restriction. I don't understand completely what you mean with option 4, but go for it. I'll let you know once you have the code whether I accept it or not XD.

Once, you are done with it I'll be happy to integrate everything and upload it to ankiweb. Now that I think about it, I'll add a list of collaborators in the description. It's bunkers that people actually use this and like it.

Thanks for your effort.

**Comment by ribbanya** [comment]
> I like to type annotate all functions,

No problem; I'm used to typed languages anyway so I prefer to as well. I was a bit lazy with this implementation.

> I would like to replace the `exit(1)` for a `raise Exception(f"{pinyin} isn't a pinyin")`.

I actually only did this because I saw it [in the original codebase](https://github.com/helq/pinyin-beginners-anki-deck/blob/f30726ff6848220d98bfc66bd272b0fac1da2e79/generate-deck.py#L269-L271). I can change them all to `Exception`s, though. I prefer that as well.

> I am inclined for option 2 too. Preferably, everything should be packed in a single file and the user should be able to tweak as they please. Adding a few KB to your phone/PC for support on both pinyin and bomopofo shouldn't be a restriction.

Yeah. CSS isn't very user-friendly, but as far as I know there's not a better way to do it without writing an entire extension.

> I don't understand completely what you mean with option 4, but go for it.

Sorry for the weird wording. I just meant pinyin and zhuyin being presented together by default. That's how the deck looks in the current pull request.

I'll take a look at how `{{type:Pinyin}}` checks and highlights the correct answer. I'd like there to be a single input box that can detect either correct answer (pinyin or zhuyin) and then highlight it in both lettering systems.

**Comment by ribbanya** [comment]
Okay, I did some code cleanup as well as some restructuring. JS and CSS now live in their own files, and are inlined into the HTML templates at generation time. Please let me know if you don't like it.

**Comment by ribbanya** [comment]
@helq Could you explain [this](https://github.com/helq/pinyin-beginners-anki-deck/blob/f30726ff6848220d98bfc66bd272b0fac1da2e79/notes/Chinese%20Tones/front-01.html#L72)? It obviously works but I do not understand it at all.

Anki's handlebars swaps in the field, which looks something like

> [sound:fen1_1.mp3] MOS fen1 MOS ㄈㄣˉ MOS [fən] EOL 
[sound:sheng1_1.mp3] MOS sheng1 MOS ㄕㄥˉ MOS [ʂəŋ] EOL 
[sound:ga1_3.mp3] MOS ga1 MOS ㄍㄚˉ MOS [kɑ] EOL 
[sound:an1_1.mp3] MOS an1 MOS ㄢˉ MOS [an] EOL 
[sound:lao1_6.mp3] MOS lao1 MOS ㄌㄠˉ MOS [lɑʊ̯] EOL 
[sound:xie1_5.mp3] MOS xie1 MOS ㄒㄧㄝˉ MOS [ɕiɛ] EOL 
...

so the final Javascript (I guess?) looks something like
```js
posibilities = getElems( function EOL() {/*EOL [sound:fen1_1.mp3] MOS fen1 MOS ㄈㄣˉ MOS [fən] EOL 
[sound:sheng1_1.mp3] MOS sheng1 MOS ㄕㄥˉ MOS [ʂəŋ] EOL 
[sound:ga1_3.mp3] MOS ga1 MOS ㄍㄚˉ MOS [kɑ] EOL 
[sound:an1_1.mp3] MOS an1 MOS ㄢˉ MOS [an] EOL 
[sound:lao1_6.mp3] MOS lao1 MOS ㄌㄠˉ MOS [lɑʊ̯] EOL 
[sound:xie1_5.mp3] MOS xie1 MOS ㄒㄧㄝˉ MOS [ɕiɛ] EOL EOL*/} );
```

... and then `fun.toString()` returns... what, exactly? 😕

**Comment by ribbanya** [comment]
Turns out `{{type:}}` on multiple input fields is going to be [more complicated than I thought](https://anki.tenderapp.com/discussions/ankidesktop/14814-multiple-typing-fields), so I'd like to shelve it for now. I didn't realise it was a built-in Anki feature.

For now the code should be in a mergeable state. Some of the styling could use some work, though.

**Comment by helq** [comment]
Wow! Thanks a lot for all your effort.

> I actually only did this because I saw it in the original codebase. I can change them all to Exceptions, though. I prefer that as well.

Lol. Yeah, I'm not that consistent. I mostly wrote this as a script for myself. I never thought anybody would care to look at it. I was so wrong.

I'll check whether everything works on my end, in Anki desktop and in AnkiDroid. I'll accept it afterwards. You'll have to give me a week though. I am at the of the end of the semester and I have a lot of projects to finish.

Thanks again for all the amazing work! I hope those improvements help the deck to reach even more people. Chinese is hard, coding is hard, finding free tools is hard. Fortunately there is kind people like you.

Best,
helq

**Comment by ribbanya** [comment]
> I'll check whether everything works on my end, in Anki desktop and in AnkiDroid. I'll accept it afterwards. You'll have to give me a week though. I am at the of the end of the semester and I have a lot of projects to finish.

No problem. I have more ideas for improvements (that I want to have in the deck for myself anyway) but I'm also pretty busy this week. I'll put them in a new pull request when I get around to them, but this one and #7 are ready to be reviewed.

**Comment by helq** [comment]
Hey @ribbanya, I finally got to it. Sorry for the very long wait. I tested it in Anki desktop and it worked like charm. I hope it does too in AnkiDroid and iOS. (Grad school is very time consuming :S.)

I also updated the README. Thanks a lot

**Pull request merged**
